<?php

/*****************************************************/
/*             Clase ProvinceRepository              */
/*      Contiene una funciones necesarias para la    */
/*                  Entidad Country                  */
/*                                                   */
/*****************************************************/

/**
 * Description of ProvinceRepository
 *
 * @author Checo
 */
namespace JMPC\PetFriends\ProtectorsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* ProvinceRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class ProvinceRepository extends EntityRepository
{
    
	//Devuelve todas las provincias asociadas a un pais
    public function findByCountryId($pais_id)
    {
        $query = $this->getManager()->createQuery("
            SELECT province
            FROM JMPCPetFriendsProtectorsBundle:Province ciudades
            LEFT JOIN ciudades.pais pais
            WHERE pais.id = :pais_id")->setParameter('codigo_id', $pais_id);
        return $query->getArrayResult();
    }
}