<?php

namespace Proxies\__CG__\JMPC\PetFriends\ProtectorsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnimalLost extends \JMPC\PetFriends\ProtectorsBundle\Entity\AnimalLost implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'idanimalperdido', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'nombre', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'tipo', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'raza', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'tamano', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'color', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'sexo', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'comportamiento', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'mensaje', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'pais', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'ciudad', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'direccion', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'fotografia', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'fechaperdida', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'chip', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'encontrado', 'slug', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'fotografiaArchivo', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'idusuariomascperd');
        }

        return array('__isInitialized__', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'idanimalperdido', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'nombre', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'tipo', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'raza', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'tamano', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'color', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'sexo', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'comportamiento', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'mensaje', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'pais', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'ciudad', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'direccion', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'fotografia', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'fechaperdida', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'chip', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'encontrado', 'slug', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'fotografiaArchivo', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\AnimalLost' . "\0" . 'idusuariomascperd');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AnimalLost $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdanimalperdido()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdanimalperdido();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdanimalperdido', array());

        return parent::getIdanimalperdido();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaza($raza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaza', array($raza));

        return parent::setRaza($raza);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaza', array());

        return parent::getRaza();
    }

    /**
     * {@inheritDoc}
     */
    public function setTamano($tamano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTamano', array($tamano));

        return parent::setTamano($tamano);
    }

    /**
     * {@inheritDoc}
     */
    public function getTamano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTamano', array());

        return parent::getTamano();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setComportamiento($comportamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComportamiento', array($comportamiento));

        return parent::setComportamiento($comportamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getComportamiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComportamiento', array());

        return parent::getComportamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensaje($mensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensaje', array($mensaje));

        return parent::setMensaje($mensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensaje', array());

        return parent::getMensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', array($pais));

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', array());

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotografia($fotografia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotografia', array($fotografia));

        return parent::setFotografia($fotografia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotografia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotografia', array());

        return parent::getFotografia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPerdida($fechaperdida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPerdida', array($fechaperdida));

        return parent::setFechaPerdida($fechaperdida);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPerdida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPerdida', array());

        return parent::getFechaPerdida();
    }

    /**
     * {@inheritDoc}
     */
    public function setChip($chip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChip', array($chip));

        return parent::setChip($chip);
    }

    /**
     * {@inheritDoc}
     */
    public function getChip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChip', array());

        return parent::getChip();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncontrado($encontrado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncontrado', array($encontrado));

        return parent::setEncontrado($encontrado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncontrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncontrado', array());

        return parent::getEncontrado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuariomascperd(\JMPC\PetFriends\ProtectorsBundle\Entity\User $idusuariomascperd = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuariomascperd', array($idusuariomascperd));

        return parent::setIdusuariomascperd($idusuariomascperd);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuariomascperd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuariomascperd', array());

        return parent::getIdusuariomascperd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotografiaArchivo($fotografiaArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotografiaArchivo', array($fotografiaArchivo));

        return parent::setFotografiaArchivo($fotografiaArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotografiaArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotografiaArchivo', array());

        return parent::getFotografiaArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function slugify($text)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'slugify', array($text));

        return parent::slugify($text);
    }

}
