<?php

namespace Proxies\__CG__\JMPC\PetFriends\ProtectorsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \JMPC\PetFriends\ProtectorsBundle\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'titulo', 'autor', 'contenido', 'imagen', 'tags', 'comentarios', 'creado', 'actualizado', 'slug', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\Post' . "\0" . 'imagenArchivo');
        }

        return array('__isInitialized__', 'id', 'titulo', 'autor', 'contenido', 'imagen', 'tags', 'comentarios', 'creado', 'actualizado', 'slug', '' . "\0" . 'JMPC\\PetFriends\\ProtectorsBundle\\Entity\\Post' . "\0" . 'imagenArchivo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutor($autor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutor', array($autor));

        return parent::setAutor($autor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutor', array());

        return parent::getAutor();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido($contenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', array($contenido));

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido($length = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', array($length));

        return parent::getContenido($length);
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', array($imagen));

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', array());

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', array($tags));

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreado($creado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreado', array($creado));

        return parent::setCreado($creado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreado', array());

        return parent::getCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setActualizado($actualizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActualizado', array($actualizado));

        return parent::setActualizado($actualizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getActualizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActualizado', array());

        return parent::getActualizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedValue', array());

        return parent::setUpdatedValue();
    }

    /**
     * {@inheritDoc}
     */
    public function addComments(\JMPC\PetFriends\ProtectorsBundle\Entity\Comments $comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComments', array($comentarios));

        return parent::addComments($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComments(\JMPC\PetFriends\ProtectorsBundle\Entity\Comments $comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComments', array($comentarios));

        return parent::removeComments($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', array());

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenArchivo($imagenArchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenArchivo', array($imagenArchivo));

        return parent::setImagenArchivo($imagenArchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenArchivo', array());

        return parent::getImagenArchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function slugify($text)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'slugify', array($text));

        return parent::slugify($text);
    }

    /**
     * {@inheritDoc}
     */
    public function addComentario(\JMPC\PetFriends\ProtectorsBundle\Entity\Comments $comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComentario', array($comentarios));

        return parent::addComentario($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComentario(\JMPC\PetFriends\ProtectorsBundle\Entity\Comments $comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComentario', array($comentarios));

        return parent::removeComentario($comentarios);
    }

}
